version: v2.0

platform: gke

image: us-central1-docker.pkg.dev/cloudaware-breeze/partner-artifacts/breeze-agent:2.0

tls:
  fromSecrets: true
  cert:
    secretName: "breeze-tls-secret"
    key: "tls.crt"
  key:
    secretName: "breeze-tls-secret"
    key: "tls.key"

resources:
    requests:
        memory: "64Mi"
        cpu: "30m"
    limits:
        memory: "128Mi"
        cpu: "50m"

serviceAccount:
    create: true
